// web/src/app/reset-password/page.tsx
'use client'

import { useState, useEffect, useRef, type FormEvent } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { sendCode, resetPassword as apiResetPassword } from '@/lib/api'
import { useI18n } from '@/lib/i18n'
import styles from './page.module.css'

type Step = 'code' | 'reset'

const COUNTDOWN_SECONDS = 60

export default function ResetPasswordPage() {
  const router = useRouter()

  const { t } = useI18n()

  const [step, setStep] = useState<Step>('code')
  const [email, setEmail] = useState('')
  const [code, setCode] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [error, setError] = useState('')
  const [successMsg, setSuccessMsg] = useState('')
  const [loading, setLoading] = useState(false)
  const [countdown, setCountdown] = useState(0)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current)
    }
  }, [])

  function startCountdown() {
    setCountdown(COUNTDOWN_SECONDS)
    timerRef.current = setInterval(() => {
      setCountdown((prev) => {
        if (prev <= 1) {
          if (timerRef.current) clearInterval(timerRef.current)
          timerRef.current = null
          return 0
        }
        return prev - 1
      })
    }, 1000)
  }

  async function handleSendCode(e: FormEvent) {
    e.preventDefault()
    if (loading || countdown > 0) return

    setError('')
    setSuccessMsg('')
    setLoading(true)

    try {
      await sendCode(email, 'reset')
      setSuccessMsg(t('auth.codeSent', { email }))
      startCountdown()
      setStep('reset')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to send code')
    } finally {
      setLoading(false)
    }
  }

  async function handleReset(e: FormEvent) {
    e.preventDefault()
    if (loading) return

    setError('')
    setSuccessMsg('')
    setLoading(true)

    try {
      await apiResetPassword(email, code, newPassword)
      router.push('/login/')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Password reset failed')
    } finally {
      setLoading(false)
    }
  }

  async function handleResend() {
    if (countdown > 0) return

    setError('')
    setSuccessMsg('')
    setLoading(true)

    try {
      await sendCode(email, 'reset')
      setSuccessMsg('Reset code resent')
      startCountdown()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to resend code')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className={styles.page}>
      <div className={styles.formCard}>
        <h1 className={styles.title}>{t('reset.title')}</h1>
        <p className={styles.description}>
          {step === 'code'
            ? 'Enter your email to receive a reset code'
            : 'Enter the code and choose a new password'}
        </p>

        {step === 'code' ? (
          <form className={styles.form} onSubmit={handleSendCode}>
            {error && <div className={styles.error}>{error}</div>}

            <div className={styles.field}>
              <label className={styles.label} htmlFor="email">{t('auth.email')}</label>
              <input
                id="email"
                className={styles.input}
                type="email"
                required
                placeholder={t('auth.emailPlaceholder')}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>

            <button
              type="submit"
              className={styles.button}
              disabled={loading}
            >
              {loading ? t('auth.sending') : t('auth.sendResetCode')}
            </button>
          </form>
        ) : (
          <form className={styles.form} onSubmit={handleReset}>
            {error && <div className={styles.error}>{error}</div>}
            {successMsg && <div className={styles.success}>{successMsg}</div>}

            <div className={styles.field}>
              <label className={styles.label} htmlFor="code">{t('auth.code')}</label>
              <input
                id="code"
                className={styles.codeInput}
                type="text"
                inputMode="numeric"
                required
                maxLength={6}
                placeholder={t('auth.codePlaceholder')}
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
              />
            </div>

            <div className={styles.field}>
              <label className={styles.label} htmlFor="newPassword">{t('reset.newPassword')}</label>
              <input
                id="newPassword"
                className={styles.input}
                type="password"
                required
                minLength={6}
                placeholder={t('auth.passwordPlaceholder')}
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
              />
            </div>

            <button
              type="submit"
              className={styles.button}
              disabled={loading}
            >
              {loading ? t('reset.resetting') : t('reset.button')}
            </button>

            <div className={styles.resendArea}>
              {countdown > 0 ? (
                <span>{t('auth.resendIn', { s: countdown })}</span>
              ) : (
                <button
                  type="button"
                  className={styles.resendButton}
                  onClick={handleResend}
                  disabled={loading}
                >
                  {t('auth.resend')}
                </button>
              )}
            </div>
          </form>
        )}

        <div className={styles.footer}>
          <Link href="/login/">{t('reset.rememberPassword')}</Link>
        </div>
      </div>
    </div>
  )
}

// web/src/routes/reset-password/+page.svelte
<script lang="ts">
  import { sendCode, resetPassword } from '$lib/api/index.js'
  import { goto } from '$app/navigation'

  let step = $state<'code' | 'reset'>('code')
  let email = $state('')
  let code = $state('')
  let password = $state('')
  let error = $state('')
  let loading = $state(false)
  let codeSent = $state(false)
  let countdown = $state(0)
  let timer: ReturnType<typeof setInterval> | null = null

  async function handleSendCode(e: Event) {
    e.preventDefault()
    error = ''
    loading = true
    try {
      await sendCode(email, 'reset')
      codeSent = true
      step = 'reset'
      countdown = 60
      timer = setInterval(() => {
        countdown--
        if (countdown <= 0 && timer) clearInterval(timer)
      }, 1000)
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to send code'
    } finally {
      loading = false
    }
  }

  async function handleReset(e: Event) {
    e.preventDefault()
    error = ''
    loading = true
    try {
      await resetPassword(email, code, password)
      goto('/login')
    } catch (err) {
      error = err instanceof Error ? err.message : 'Password reset failed'
    } finally {
      loading = false
    }
  }
</script>

<svelte:head>
  <title>Reset Password - YoYOapi</title>
</svelte:head>

<div class="form-page">
  <h2>Reset Password</h2>

  {#if step === 'code'}
    <form onsubmit={handleSendCode}>
      {#if error}
        <div class="error">{error}</div>
      {/if}
      <label>
        Email
        <input type="email" bind:value={email} required placeholder="you@example.com" />
      </label>
      <button type="submit" disabled={loading}>
        {loading ? 'Sending...' : 'Send Reset Code'}
      </button>
    </form>
  {:else}
    <form onsubmit={handleReset}>
      {#if error}
        <div class="error">{error}</div>
      {/if}
      <p class="info">Reset code sent to {email}</p>
      <label>
        Verification Code
        <input type="text" bind:value={code} required maxlength={6} placeholder="123456" />
      </label>
      <label>
        New Password
        <input type="password" bind:value={password} required minlength={6} placeholder="At least 6 characters" />
      </label>
      <button type="submit" disabled={loading || password.length < 6}>
        {loading ? 'Resetting...' : 'Reset Password'}
      </button>
      {#if countdown > 0}
        <p class="hint">Resend code in {countdown}s</p>
      {:else}
        <button type="button" class="link-btn" onclick={() => { step = 'code'; codeSent = false }}>
          Resend code
        </button>
      {/if}
    </form>
  {/if}

  <p class="hint">
    Remember your password? <a href="/login">Sign In</a>
  </p>
</div>

<style>
  .form-page {
    max-width: 400px;
    margin: 2rem auto;
  }
  h2 {
    margin-bottom: 1.5rem;
  }
  form {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  label {
    display: flex;
    flex-direction: column;
    gap: 0.3rem;
    font-size: 0.9rem;
    color: var(--text-secondary);
  }
  input {
    padding: 0.6rem 0.8rem;
    border: 1px solid var(--border);
    border-radius: var(--radius);
  }
  button {
    padding: 0.7rem;
    background: var(--primary);
    color: white;
    border: none;
    border-radius: var(--radius);
    font-weight: 600;
    cursor: pointer;
  }
  button:disabled {
    opacity: 0.6;
  }
  .link-btn {
    background: none;
    color: var(--primary);
    padding: 0;
    font-weight: normal;
    font-size: 0.85rem;
  }
  .error {
    background: #fef2f2;
    color: var(--error);
    padding: 0.7rem;
    border-radius: var(--radius);
    font-size: 0.9rem;
  }
  .info {
    font-size: 0.85rem;
    color: var(--text-secondary);
  }
  .hint {
    text-align: center;
    font-size: 0.85rem;
    color: var(--text-secondary);
    margin-top: 0.5rem;
  }
</style>
