// web/src/routes/login/+page.svelte
<script lang="ts">
  import { login } from '$lib/api/index.js'
  import { setAuth } from '$lib/stores/auth.js'
  import { goto } from '$app/navigation'

  let email = $state('')
  let password = $state('')
  let error = $state('')
  let loading = $state(false)

  async function handleLogin(e: Event) {
    e.preventDefault()
    error = ''
    loading = true
    try {
      const result = await login(email, password)
      setAuth(result.apiKey, result.user as any)
      goto('/dashboard')
    } catch (err) {
      error = err instanceof Error ? err.message : 'Login failed'
    } finally {
      loading = false
    }
  }
</script>

<svelte:head>
  <title>Login - YoYOapi</title>
</svelte:head>

<div class="form-page">
  <h2>Sign In</h2>
  <form onsubmit={handleLogin}>
    {#if error}
      <div class="error">{error}</div>
    {/if}
    <label>
      Email
      <input type="email" bind:value={email} required placeholder="you@example.com" />
    </label>
    <label>
      Password
      <input type="password" bind:value={password} required placeholder="••••••••" />
    </label>
    <button type="submit" disabled={loading}>
      {loading ? 'Signing in...' : 'Sign In'}
    </button>
    <p class="hint">
      <a href="/reset-password">Forgot password?</a>
    </p>
    <p class="hint">
      Don't have an account? <a href="/register">Register</a>
    </p>
  </form>
</div>

<style>
  .form-page {
    max-width: 400px;
    margin: 2rem auto;
  }
  h2 {
    margin-bottom: 1.5rem;
  }
  form {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  label {
    display: flex;
    flex-direction: column;
    gap: 0.3rem;
    font-size: 0.9rem;
    color: var(--text-secondary);
  }
  input {
    padding: 0.6rem 0.8rem;
    border: 1px solid var(--border);
    border-radius: var(--radius);
  }
  button {
    padding: 0.7rem;
    background: var(--primary);
    color: white;
    border: none;
    border-radius: var(--radius);
    font-weight: 600;
    cursor: pointer;
  }
  button:disabled {
    opacity: 0.6;
  }
  .error {
    background: #fef2f2;
    color: var(--error);
    padding: 0.7rem;
    border-radius: var(--radius);
    font-size: 0.9rem;
  }
  .hint {
    text-align: center;
    font-size: 0.85rem;
    color: var(--text-secondary);
  }
</style>

// web/src/app/login/page.tsx
'use client'

import { useState, type FormEvent } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { login as apiLogin } from '@/lib/api'
import { useAuth } from '@/lib/auth-context'
import { useI18n } from '@/lib/i18n'
import styles from './page.module.css'

export default function LoginPage() {
  const router = useRouter()
  const { login: authLogin } = useAuth()

  const { t } = useI18n()

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    if (loading) return

    setError('')
    setLoading(true)

    try {
      const result = await apiLogin(email, password)
      authLogin(result.apiKey, result.user)
      router.push('/dashboard')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Login failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className={styles.page}>
      <div className={styles.formCard}>
        <h1 className={styles.title}>{t('login.title')}</h1>
        <p className={styles.description}>Sign in to your account to continue</p>

        <form className={styles.form} onSubmit={handleSubmit}>
          {error && <div className={styles.error}>{error}</div>}

          <div className={styles.field}>
            <label className={styles.label} htmlFor="email">{t('auth.email')}</label>
            <input
              id="email"
              className={styles.input}
              type="email"
              required
              placeholder={t('auth.emailPlaceholder')}
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>

          <div className={styles.field}>
            <label className={styles.label} htmlFor="password">{t('auth.password')}</label>
            <input
              id="password"
              className={styles.input}
              type="password"
              required
              placeholder={t('auth.passwordPlaceholder')}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>

          <button
            type="submit"
            className={styles.button}
            disabled={loading}
          >
            {loading ? t('login.loading') : t('login.button')}
          </button>
        </form>

        <div className={styles.footer}>
          <Link href="/reset-password/">{t('login.forgot')}</Link>
          <span className={styles.separator}>&middot;</span>
          <Link href="/register/">{t('login.noAccount')}</Link>
        </div>
      </div>
    </div>
  )
}
